# Official docker image.
image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  - apk add --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/edge/community nodejs-npm
  - npm i -g heroku

deploy-develop:
  stage: deploy
  script:
    - docker run -t -v $PWD:/app --workdir /app microsoft/dotnet:2.1-sdk bash -c "dotnet restore && dotnet publish -c Release -o ./bin/Release/PublishOutput"
    - docker build -t $CI_REGISTRY/my-awesome-app-dev/web .
    - docker push $CI_REGISTRY/my-awesome-app-dev/web
    # above two commands can be replaced with: "heroku container:push web --app my-awesome-app-dev"
    - heroku container:release web --app my-awesome-app-dev
  only:
    - develop
